name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, unlocked]

jobs:
  validation:
    name: Validating
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Code Format
        run: yarn format:check

      - name: Code Lint
        run: yarn lint
